"""empty message

Revision ID: 647d2de5c3be
Revises: 
Create Date: 2020-04-07 11:55:19.881239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647d2de5c3be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'flag',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'flag',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
